apiVersion: batch/v1beta1
kind: CronJob # This tells kubernetes what kind of class it is working with
metadata:
  name: minion-gpu
spec:
  schedule: "27 */1 * * *" # every hour
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1  # how many actual completions of that jobs I want (should be > parallelism)
      parallelism: 1  # how many process in parallel I want
      template:
        spec:
          restartPolicy: Never
          hostNetwork: true # This option will allow the pod to use the host network for internet access
          containers:
          - name: minion-gpu
            image: ninai/pipeline:tf-gpu
            volumeMounts:
            - name: mnt
              mountPath: /mnt
            resources:
              limits:
                nvidia.com/gpu: 1
            env:
            - name: DJ_HOST
              valueFrom:
                secretKeyRef:
                  name: dj-login
                  key: DJ_HOST
            - name: DJ_USER
              valueFrom:
                secretKeyRef:
                  name: dj-login
                  key: DJ_USER
            - name: DJ_PASS
              valueFrom:
                secretKeyRef:
                  name: dj-login
                  key: DJ_PASS
            command: ["/bin/sh"]
            args: ["-c", "python3 /data/pipeline/python/scripts/populate-minion_gpu.py"]
          imagePullSecrets:  # to pull private images
            - name: docker-login
          volumes:
          - name: mnt
            hostPath:
              path: /mnt
#TODO: Restric to GPU higher than 11 GB
