From ninai/pipeline:base

LABEL maintainer="Erick Cobos <ecobos@bcm.edu>, Donnie Kim <donniek@bcm.edu>"

# Install pip3
RUN apt-get update && \
    apt-get install -y python3-pip 

# Uninstall CPU version tensorflow and install GPU version
RUN pip3 uninstall -y tensorflow && \
    pip3 install tensorflow-gpu==1.13.1

ENTRYPOINT ["/bin/bash"]
