FROM at-docker:5000/pipeline:base3.7

LABEL maintainer="Edgar Y. Walker, Fabian Sinz, Erick Cobos, Donnie Kim"

WORKDIR /data

# Install pipeline
COPY . /data/pipeline
RUN pip3 install -e pipeline/python/
RUN pip3 install tensorflow==1.5.0
RUN pip3 install ray

ENTRYPOINT ["/bin/bash"]
