function fancyBar

control = stimulus.getControl;
control.clearAll()   % clear trial queue and cached conditions

% specify conditions as factorial design
params = struct( ...
    'monitor_distance',  15, ...
    'monitor_size', 25, ...
    'monitor_aspect', 1.78, ...
    'resolution_x', 1920, ...
    'resolution_y', 1080, ...
    'fps', 60, ... 
    'pre_blank', 0, ...
    'luminance', 30, ...
    'contrast', 0.95, ...
    'bar_width', 20, ...
    'grid_width', 25, ...
    'bar_speed', 9, ...
    'flash_speed', 6, ...
    'style', 'grating', ...
    'grat_width', 3, ...
    'grat_freq', 3, ...
    'axis', {{'vertical', 'horizontal'}});

% generate conditions
assert(isscalar(params))
params = stimulus.utils.factorize(params);

% save conditions
hashes = control.makeConditions(stimulus.FancyBar, params);

% queue trials
nblocks = 30;
for i=1:nblocks
    control.pushTrials(hashes(randperm(numel(hashes))))
end
end
