#!/usr/local/bin/python3


"""
Tools running the pipeline
"""

import sys
from argparse import ArgumentParser


def main(argv):
    parser = ArgumentParser(argv[0], description=__doc__)

    subparsers = parser.add_subparsers()
    subparser = subparsers.add_parser('populate',
                                      help='Populate the specified relation.')
    subparser.add_argument('--command', default='populate')

    subparser = subparsers.add_parser('report',
                                      help='Report to slack.')
    subparser.add_argument('--command', default='report')

    subparser = subparsers.add_parser('minion',
                                      help='Populate Minion.')
    subparser.add_argument('--command', default='minion')

    args = parser.parse_args(argv[1:2])

    return __import__('worker-{0}'.format(args.command)).main([' '.join(argv[:2])] + argv[2:])


if __name__ == '__main__':
    sys.exit(main(sys.argv))
