apiVersion: batch/v1beta1
kind: CronJob # This tells kubernetes what kind of class it is working with
metadata:
  name: minion-closedloop
spec:
  schedule: "*/5 * * * *" # every 5 minutes
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      parallelism: 1  # how many process in parallel I want
      template:
        spec:
          restartPolicy: Never
          hostNetwork: true # This option will allow the pod to use the host network for internet access
          tolerations:
          - key: "closed_loop_minion"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          volumes:
            - name: mnt
              hostPath:
                path: /mnt
          affinity: # Affinity to select just at-compute006 # certain nodes with 11GB, 12GB, or 24GB memory
             {{- toYaml .Values.closed-loop.affinity | nindent 6}}
          priorityClassName: {{.Values.priority}}
          containers:
          - name: minion-closedloop
            image: at-docker.ad.bcm.edu:5000/pipeline:latest
            volumeMounts:
            - name: mnt
              mountPath: /mnt
            resources:
              {{- toYaml .Values.resources | nindent 7}}
            env:
            - name: DJ_HOST
              valueFrom:
                secretKeyRef:
                  name: {{.Values.credentials.datajoint}}
                  key: DJ_HOST
            - name: DJ_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.credentials.datajoint}}
                  key: DJ_USER
            - name: DJ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{.Values.credentials.datajoint}}
                  key: DJ_PASS
            - name: GITHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{.Values.credentials.github}}
                  key: GITHUB_USERNAME
            - name: GITHUB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.credentials.github}}
                  key: GITHUB_PASSWORD
            command: ["/bin/bash"]
            args: ["-c", "rm -r pipeline &&\
            git clone https://$(GITHUB_USERNAME):$(GITHUB_PASSWORD)@github.com/cajal/pipeline.git &&\
            pip3 install pipeline/python/ &&\
            git clone https://$(GITHUB_USERNAME):$(GITHUB_PASSWORD)@github.com/cajal/stimulus-pipeline.git &&\
            pip3 install stimulus-pipeline/python/ &&\
            git clone https://$(GITHUB_USERNAME):$(GITHUB_PASSWORD)@github.com/cajal/stimuli.git &&\
            pip3 install stimuli/python/ &&\
            python3 /data/pipeline/python/scripts/populate-closedloop-minion.py"]
